### PR TITLE
Initial commit of behat test setup.

### PR DESCRIPTION
**Pull request by cooperaj**
Behat is configured to use the laravel-behat extension and my slightly different (but IMO useful) way of laying out the test folder structure has been done.

Essentially each context file is mostly empty and all test definitions are broken out into related functionality traits.

I've also taken the liberty of binding the app/HMS folder to the HMS\\ namespace (since I have some behat code that lives there)

### CODE REVIEW

**Comment by cooperaj** [comment]
Worth pointing out that I added a dummy test to the setup so that it's possible to see vaguely how things work. Once actual tests exist then it'll be deleted I imagine.

**Comment by geeksareforlife** [comment]
I do not understand most of this, but the bits I do don't seem to conflict with the main system.  I'm happy to merge, but would appreciate a second opinion

**Comment by cooperaj** [comment]
Seems this covers (at least paritally) issue #12 ?

**Comment by dpslwk** [comment]
all looks good to me and covers whats needed to start with

**Pull request merged**
