### PR TITLE
Links

### PR DESCRIPTION
**Pull request by dpslwk**

### CODE REVIEW

**Comment by dpslwk** [comment]
OK this is ready for review but I think @Hodgy and @cooperaj might want to take a look at the `LinkFactory` and the `public function updateWithRequest(LinkRequest $request)` method on the `Link` entity

**Comment by cooperaj** [comment]
You're using static calls in the LinkFactory.

For testing and SOLID principles the LinkFactory is an instantiated object the same as any other, one that can be dependency injected etc. So these should just be normal non-static methods.

**Comment by dpslwk** [comment]
@cooperaj Updated the factory to normal methods

**Comment by cooperaj** [comment]
looks good

**Pull request merged**
