### PR TITLE
Transition to yaml files for entity persistence mapping.

### PR DESCRIPTION
**Pull request by cooperaj**

### CODE REVIEW

**Comment by geeksareforlife** [comment]
Just a quick question on this.

The YAML file for Permissions is in the Doctrine namespace, but the one for Role is in the HMS namespace - is that right?

**Comment by roberthunt** [comment]
Yeah, the Permission class (Entity) is provided as part of the laravel-doctrine library, as it only consists of an id and a name there isn't a whole lot of point in creating our own copy of it as we're unlikely to be customising it.

**Comment by geeksareforlife** [comment]
Makes sense.

How would I test this PR? It doesn't seem to change anything that would actually affect the system

**Comment by cooperaj** [comment]
You pull it it. Run 

```php artisan doctrine:migrations:reset```
and
```php artisan doctrine:migrations:migrate```

And if you can register a user and be logged in as it (i.e. nothing has really changed) it's all working.

**Pull request merged**
