### PR TITLE
Rifd views

### LINKED ISSUE #206: Ability to reactivate Pin for RFID enrolment
Trustees and Membership team should be able to reactivate pins

### LINKED ISSUE #207: View Pins

### LINKED ISSUE #208: RfidTag View and edit

### PR DESCRIPTION
**Pull request by dpslwk**
rfidTag & pin views and ability to edit rfidTags and reactivate pins

closes #206 
closes #207 
closes #208

### CODE REVIEW

**Comment by dpslwk** [comment]
this has not been added to the nav yet but you can go to 
http://hmsdev/rfid_tags?user=1
to test

**Comment by geeksareforlife** [comment]
The route doesn't really feel consistent with the rest of the app.  RFID tags are resources that belong to a user, so shouldn't the route be something like:

/users/{user-id}/rfid_tags/

??

**Comment by dpslwk** [comment]
Nah, because HMS is always about the user, every damn route would end up as /users/{user}/something



Matt

**Comment by geeksareforlife** [comment]
I'm not sure I buy that dude.

A tools booking, for example, would still be `/tools/{tool-id}/bookings/{booking-id}` - this would belong to a user, and the view permission is checked in code.

If you want to look at one tag, I'm fine with `/rfid_tags/{tag-id}` or for `/rfid_tags/` to show all the tags you have access to (fine for users, not so good for admins).

But if you want to look at tags that a user owns, I think the root above is what we need

**Comment by ocatelle** [comment]
Before merging I'd consider changing line 6 of resources/views/emails/membership/eighteenCongratulations.blade.php from 
> This email is just to let you know your Nottingham Hackspace membership has been migrated from its Young Hacker status.

to

> This email is just to let you know your Nottingham Hackspace membership has been migrated to Full Member from its Young Hacker status. This does not affect your access to the space, use of any of the tools, or any other part of your membership.

or some similar text to clarify to the recipient that the change in status does not affect their membership.

**Comment by dpslwk** [comment]
All text copy for emails and pages is going to get a huge review from the trustees and teams (where appropriate) before things go live. 
Anything going in now should be treated with “this is a place holder” view

Matt

**Pull request merged**
