### PR TITLE
Added softDelete trait and add it to User Entity

### PR DESCRIPTION
**Pull request by Hodgy**

### CODE REVIEW

**Comment by geeksareforlife** [comment]
There's going to be a lot of stupid questions from me until I get this all in my head!  How does this differ from the

```
LaravelDoctrine\Extensions\SoftDeletes\SoftDeleteableExtension::class
```

that is enabled in `config/doctrine.php` or this this related to that?

**Comment by roberthunt** [comment]
The `config/doctrine.php` enables the use of the extension (pulled in via composer) which @cooperaj enabled on Sunday, this actually adds the soft delete functionality to the `User` entity.

**Comment by geeksareforlife** [comment]
awesome, that makes sense

**Comment by Hodgy** [comment]
Need to update this now that #33 has been merged

**Pull request merged**
