### PR TITLE
JS: need to server the manifest file when using extract

### PR DESCRIPTION
**Pull request by dpslwk**
https://laravel.com/docs/5.4/mix#vendor-extraction

### CODE REVIEW

**Comment by dpslwk** [comment]
Foundation is still broken mind, there seems to be some big issue with jQuery, foundation and Laravel Mix

think we may need to update the .js files as per the last post on this issue
https://github.com/JeffreyWay/laravel-mix/issues/229
but there is also this massive issue I've not yet ready thought, though the last comment suggest somethings might change for the better with foundation 6.4
https://github.com/zurb/foundation-sites/issues/7386

**Comment by mathw** [comment]
This is quite frustrating, because I spent ages getting it working before - was this triggered by the Laravel update?

**Comment by roberthunt** [comment]
@matw yes, with Laravel 5.4 they introduced "Laravel Mix" which is a successor to "Laravel Elixer" and is a wrapper around Webpack rather than Gulp. You can freely edit the webpack.config.js though if you need to do more advanced stuff.

**Comment by dpslwk** [comment]
@roberthunt @mathw quick an dirty fix but will do till we get our hands on 6.4
its not like we will be live before then

**Pull request merged**
