### PR TITLE
Redis for cache and session, beanstalk for queues

### PR DESCRIPTION
**Pull request by dpslwk**
Setup for redis based cache and session driver

I also reworked the migrations setup so that we can now use a mix of doctrine and eloquent migrations 
now using passports included migrations rather than the doctrine ones i did

Setup for beanstalkd queue drive and using the doctrine safe queue worked

This installs all the needed bits to run queue's via beanstalkd but still leaves the dev environment using `sync` queues by default
to test code with async queue's just update your .env file
`QUEUE_DRIVER=sync`
to
`QUEUE_DRIVER=beanstalkd`
you will likely need to restart the queue worker for it to pick up code changes
`php artisan queue:restart`

### CODE REVIEW

**Comment by cooperaj** [comment]
Any reason for beanstalkd if redis is already in place?

**Comment by dpslwk** [comment]
I had trouble running the job queue off redis, especially with the default for multiple workers. At least during startup. 


'RepRap' Matt

**Comment by dpslwk** [comment]
But that was before I switched to the doctrine safe worker. Could try moving back

'RepRap' Matt

**Comment by geeksareforlife** [comment]
This is a big change!  Why have both eloquent and doctrine migrations? wouldn't this cause issues?

**Comment by dpslwk** [comment]
actually with the changes so they each have there own folder and table they play together nicely and actually solve a DB reset issue i has not realised when i forced the passport migrations in doctrine 

Matt

**Pull request merged**
