### PR TITLE
Snackspace transactions

### PR DESCRIPTION
**Pull request by dpslwk**
add the basic user view

### CODE REVIEW

**Comment by dpslwk** [comment]
add a seeder for you

**Comment by geeksareforlife** [comment]
I now get:

```
Class ProductTableSeeder does not exist
```

during the seed

**Comment by dpslwk** [comment]
Need to do a
`composer dumpautoload`

Matt

**Comment by geeksareforlife** [comment]
thought I had, sorry

**Comment by dpslwk** [comment]
I should maybe add it to the reseed script

Matt

**Comment by geeksareforlife** [comment]
Works fine

**Pull request merged**
