### PR TITLE
Added basic member roles/permission and user seeder

### PR DESCRIPTION
**Pull request by geeksareforlife**

### CODE REVIEW

**Comment by geeksareforlife** [comment]
closes #14

**Comment by geeksareforlife** [comment]
closes #9

**Comment by geeksareforlife** [comment]
closes #8

**Comment by geeksareforlife** [comment]
You were there when I was asking this exact question yesterday? :)

Happy to change the role names to this, I will do it shortly.

Do we distinguish between roles and permissions in any way in the naming scheme?  I imagine it could get confusing

**Comment by cooperaj** [comment]
Err, missed that 😁 

No. No need to distinguish as they live in separate database tables, are represented by separate entities and have different manipulation code. It's unlikely to cause confusion.

**Comment by geeksareforlife** [comment]
Ok, updated as above.

Also, with the automated migrations, can we not name them anymore?

**Comment by roberthunt** [comment]
We can still name them if we want, the only important part of the name is that it starts with 'Version' followed by something that puts them into the correct order. I based the naming scheme after a strategy we use a work with our migration tool (FlyWay) which behaves in a similar way.

This is what I came up with:

```
HMS_VERSION = release number which the migration targets
DATE = date the migration was created in the format YYYYMMDD
INDEX = unique index starting at 1 to ensure multiple migrations on the same day are executed in the correct order
DESCRIPTION_OF_CHANGE = short description of the migration

Version{HMS_VERSION}_{DATE}_{INDEX}__{DESCRIPTION_OF_CHANGE}.php
       |                          |  |                     |
       |      UNIQUE VERSION      |  |     DESCRIPTION     |

EG:

Version1_20161015_1__create_user_table.php
Version1_20161015_2__create_password_resets_table.php
Version14_20170102_1__create_account_table.php
```

**Comment by cooperaj** [comment]
Sort of makes sense. But we're fighting the automatic naming with that. Is it not just possible to append a description to the name it comes up with? i.e.

Version20161024121537_thing_i_do_with_the_thing.php

It's just I don't see us particularly needing a release number (when I'm writing a feature full of migrations I have no real idea what version of HMS it's going to end up in? Does this mean that just before a PR is merged someone has to go through and rename a bunch of migrations?) and the index is handled by the the fact the autogenerated name uses a DATETIMESTAMP which leaves us with the above.

**Comment by geeksareforlife** [comment]
Either of these sounds good to me (I don't have the knowledge to pick one!)

The only thing I really want is the name, as then I can work out which migration I want to look at.

**Comment by Hodgy** [comment]
Adam's solutions looks like the better one to me.

**Comment by roberthunt** [comment]
Yeah, I'm happy to go with that solution. At work we know the version ahead of time as we base it on our iterations but that doesn't make sense for how we'll be using it here.

**Comment by geeksareforlife** [comment]
I guessed that, but one of the migration files was the one that added the roles and permissions - the one that existed was wrong :)

**Comment by roberthunt** [comment]
I've pushed a small change to use constants rather than strings for the roles. This will help if we use them elsewhere in the future as we don't need to worry about typos and they are defined in a single place.

I also added parentheses to the construction of the `ArrayCollection` - not strictly necessary but we should be consistent, I imagine this can be enforced by a style checker somehow.

**Comment by geeksareforlife** [comment]
That seems like a good plan

**Comment by dpslwk** [comment]
go with Adam’s Version{DATESTAMP}_{Description}

Matt

**Pull request merged**
