### PR TITLE
Added script to pass artisan commands to VM

### PR DESCRIPTION
**Pull request by geeksareforlife**
Very simple script to pass artisan scripts through the the virtual machine.

Just run

./runartisan <artisan command>

in the root directory

### CODE REVIEW

**Comment by dpslwk** [comment]
cause though larval is nice and easy for use OSX based dev no ever other OS has a compatible PHP version installed and the point of working with a vagrant box is that user don't need to install or change there host machine

**Comment by geeksareforlife** [comment]
as @dpslwk said, this is so the Dev doesn't even need to have PHP installed on their box, or work out how to SSH into the vagrant box, find the directory and run the right command

It's just a convenience really

**Comment by cooperaj** [comment]
@dpslwk Hence setting up an alias. I'd probably end up doing that. Or running the commend on a shell in the vagrant box. 

What I'm highly unlikely to be doing is running a shell script on my local machine to do processes in the VM.

By setting up these commands we're invalidating much of the laravel documentation on running things - which could provide just as much confusion to new people.

Perhaps all this can be wrapped into a single script that executes commands on the vagrant box? That way the documentation a user might find on the web is still valid (just prefixed with something)?

If we're set on providing a bunch of helper utilities/scripts could we partition them off into a folder rather then cluttering up the root?

**Comment by geeksareforlife** [comment]
That's a good idea, I'm happy for this to be a more general script

**Comment by geeksareforlife** [comment]
By the way, this script was just intended to be a preface to the artisan stuff, so you would do:

./runartisan migrate:migrate

for example

**Comment by dpslwk** [comment]
I say we add it but that this needs a update in the Readme to go with it first, with a note saying 
and where you see larval docs have 'php artisan' use './runarrtisan' instead

me i likely wont use it either as i have macOS ;)

**Pull request merged**
